frontend/controllers/AdressController.php
<?php

namespace frontend\controllers;

use Yii; 
use yii\web\Controller;
use frontend\models\Adressa;
use common\models\User;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;
use frontend\models\AdressaForm;


class AdressController extends Controller
{
    
    public function actionAbout()
    {

        $dataProvider = new ActiveDataProvider([
            'query' => User::find(),
            'pagination' => [
                'pageSize' => 4,
            ]
        ]);
        
        return $this->render('about', [
            'dataProvider' => $dataProvider,            
        ]);
    }
    

    
    public function actionView($id) 
    {   
        
        $user = User::find()->where(['id' => $id])->one();
        
        $dataProvider = new ActiveDataProvider([
            'query' => Adressa::find()->where(['user_id' => $id]),
            'pagination' => [
                'pageSize' => 5,
            ]
        ]);
        
        return $this->render('view', [
            'user' => $user,
            'dataProvider' => $dataProvider,
            
        ]);
    }
     public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        
        
        if ($model->load(Yii::$app->request->post()) ) {               

            if ($model->save()) {
                
                Yii::$app->session->setFlash('success', 'Adress update!');
                
                return $this->redirect(['adress/about']);
                
            }
        }  

        return $this->render('update', [
            'model' => $model,
        ]);
    }
    
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['adress/about']);
    }
    
    public function actionCreate($id)
    {
        
        $model = new AdressaForm();
        
         if ($model->load(Yii::$app->request->post()) && $model->add($id)) {
            //return $this->redirect(['adress/view', 'id' => $model->user_id]);
            return $this->redirect(['adress/about']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
    
    
    protected function findModel($id)
    {
        if (($model = Adressa::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    

}

frontend/controllers/VisitorController.php
<?php

namespace frontend\controllers;

use Yii; 
use yii\web\Controller;
use common\models\User;
use yii\web\NotFoundHttpException;



class VisitorController extends Controller
{
    

     public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        
        
        if ($model->load(Yii::$app->request->post()) ) {               

            if ($model->save()) {
                
                Yii::$app->session->setFlash('success', 'Adress update!');
                
                return $this->redirect(['adress/about']);
                
            }
        }  

        return $this->render('update', [
            'model' => $model,
        ]);
    }
    
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['adress/about']);
    }
    

    
    
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    

}

frontend/views/adress/_about.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;

?>

<div class="col-md-4">

    <h4><?php echo 'id - ' . Html::encode($model->id); ?></h4>
    <p><?php echo 'пользователь - ' . Html::encode($model->username); ?></p>
    <p><?php echo 'email - ' . Html::encode($model->email); ?></p>                           
    <span><?php echo Yii::$app->formatter->asDateTime($model->created_at); ?></span>
    <br>
    <?php if (Yii::$app->user->identity && Yii::$app->user->identity->equals($model)): ?>
        <a href="<?php echo Url::to(['adress/view', 'id' => $model->id]); ?>">
            <h6>Просмотр</h6>
        </a>
        <a href="<?php echo Url::to(['visitor/update', 'id' => $model->id]); ?>">
            <h6>Редактировать</h6>
        </a>
        <a href="<?php echo Url::to(['visitor/delete', 'id' => $model->id]); ?>">
            <h6>Удалить</h6>
        </a>
    <?php else: ?>
    
        <a href="<?php echo Url::to(['adress/view', 'id' => $model->id]); ?>">
            <h6>Просмотр</h6>
        </a>
    
    <?php endif; ?>
    
    <hr>

</div>

frontend/views/adress/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\Blog */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="adress-form">

    <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'post_index')->textInput()->hint('Пожалуйста, введите только цифры') ?>
    
        <?= $form->field($model, 'country')->textInput()->hint('Пожалуйста, введите двух буквенный код') ?>

        <?= $form->field($model, 'city')->textInput() ?>
            
        <?= $form->field($model, 'street')->textInput() ?>
    
        <?= $form->field($model, 'house_namber')->textInput() ?>

        <?= $form->field($model, 'office')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/adress/_view.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
/**
 *  @var Product
 *  @var get item from backend and other parameters for one product and put it in dataProvider 
 */
?>

    <div class="col-md-4">

        <h4><?php echo 'id - ' . Html::encode($model->id); ?></h4>
        <p><?php echo 'user_id - ' . Html::encode($model->user_id); ?></p>
        <p><?php echo 'почтовый индекс - ' . Html::encode($model->post_index); ?></p>                           
        <p><?php echo 'страна  - ' . Html::encode($model->country); ?></p>
        <p><?php echo 'город - ' . Html::encode($model->city); ?></p>
        <p><?php echo 'страна - ' . Html::encode($model->street); ?></p>
        <p><?php echo 'номер дома - ' . Html::encode($model->house_namber); ?></p>
        <p><?php echo 'номер офиса/квартиры - ' . Html::encode($model->office); ?></p>
        
        <br>
        <?php if (Yii::$app->user->identity && Yii::$app->user->identity->equals($model->user)): ?>
        <a href="<?php echo Url::to(['adress/update', 'id' => $model->id]); ?>">
            <h6>Редактировать</h6>
        </a>
        <a href="<?php echo Url::to(['adress/delete', 'id' => $model->id]); ?>">
            <h6>Удалить</h6>
        </a>
        <a href="<?php echo Url::to(['adress/create', 'id' => $model->user_id]); ?>">
            <h6>Создать</h6>
        </a>
        <hr> 
        <?php endif; ?>

    </div>

frontend/views/adress/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\widgets\ListView;
use yii\widgets\Pjax;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <div class="container">        
        <div class="body-content">
        
            <div class="row">
        
                <?php Pjax::begin(['id' => 'item']); ?>   
    
                    <?php
                         echo ListView::widget([
                            'dataProvider' => $dataProvider,                       
                            'layout' => "{pager}\n{items}",
                            'itemView' => '_about',
                                'options' => [
                                'tag' => 'div',
                                'class' => 'text-center',
                                'id' => 'pager', // не заполнял
                            ],
                        ]);
                    ?>
    
                <?php Pjax::end(); ?>
            </div>
            
        
        </div>           
    </div>
    
</div>

frontend/views/adress/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Blog */

$this->title = 'Create Adress';

?>
<div class="blog-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/adress/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Blog */

$this->title = 'Update Adress: ' . $model->id;
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="adress-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/adress/view.php
<?php


use yii\widgets\Pjax;
use yii\helpers\Html;
use yii\widgets\ListView;

?>


<div class="container">
    <div class="body-content">

        <div class="row">
            <div class="col-lg-12">
                
            <?php Pjax::begin(['id' => 'item']); ?> 
                
                <h4><?php echo 'id - ' . Html::encode($user->id); ?></h4>
                <p><?php echo 'пользователь - ' . Html::encode($user->username); ?></p>
                <p><?php echo 'email - ' . Html::encode($user->email); ?></p>                           
                <span><?php echo Yii::$app->formatter->asDateTime($user->created_at); ?></span>
                <br>
                <hr>
                                                
            </div>          
        </div>
        
        <div class="row">
                     
            <?php
                echo ListView::widget([
                    'dataProvider' => $dataProvider,                       
                    'layout' => "{pager}\n{items}",
                    'itemView' => '_view',
                    'options' => [
                        'tag' => 'div',
                        'class' => 'text-center',
                        'id' => 'pager', // не заполнял
                    ],
                ]);
                ?>
            
            <?php Pjax::end(); ?>
                
       
        </div>

    </div>
</div>